package es.deusto.ingenieria.prog3.easybooking.domain;

public enum Country {
	AE("United Arab Emirates"),
	AN("Netherlands Antilles"),
	AO("Angola"),
	AR("Argentina"),
	AT("Austria"),
	AZ("Azerbaijan"),
	BE("Belgium"),
	BG("Bulgaria"),
	BM("Bermuda"),
	BR("Brazil"),
	CA("Canada"),
	CH("Switzerland"),
	CL("Chile"),
	CN("China"),
	CO("Colombia"),
	CR("Costa Rica"),
	CU("Cuba"),
	CY("Cyprus"),
	CZ("Czech Republic"),
	DE("Germany"),
	DK("Denmark"),
	DO("Dominican Republic"),
	DZ("Algeria"),
	EG("Egypt"),
	ES("Spain"),
	ET("Ethiopia"),
	FI("Finland"),
	FR("France"),
	GB("United Kingdom"),
	GH("Ghana"),
	GR("Greece"),
	HK("Hong Kong"),
	HR("Croatia"),
	HT("Haiti"),
	HU("Hungary"),
	IE("Ireland"),
	IL("Israel"),
	IN("India"),
	IT("Italy"),
	JM("Jamaica"),
	JO("Jordan"),
	JP("Japan"),
	KE("Kenya"),
	KR("South Korea"),
	LB("Lebanon"),
	MA("Morocco"),
	MT("Malta"),
	MU("Mauritius"),
	MV("Maldives"),
	MX("Mexico"),
	MY("Malaysia"),
	NG("Nigeria"),
	NL("Netherlands"),
	NO("Norway"),
	PA("Panama"),
	PE("Peru"),
	PL("Poland"),
	PR("Puerto Rico"),
	PT("Portugal"),
	QA("Qatar"),
	RO("Romania"),
	RS("Serbia"),
	RU("Russia"),
	SA("Saudi Arabia"),
	SC("Seychelles"),
	SE("Sweden"),
	SG("Singapore"),
	SN("Senegal"),
	TH("Thailand"),
	TN("Tunisia"),
	TR("Turkey"),
	UA("Ukraine"),
	US("United States"),
	VE("Venezuela"),
	VI("United States Virgin Islands"),
	VN("Vietnam"),
	ZA("South Africa");
	
	private String name;
	
	Country(String name) {
		this.name = name;
	}
	
	public String getName() {
		return this.name;
	}
}